CXX = g++
CXXFLAGS = -Wall -Wextra -std=c++17
TARGET = prime-calculator
SRC = prime_calculator.cpp

all: $(TARGET)

$(TARGET): $(SRC)
	$(CXX) $(CXXFLAGS) $(SRC) -o $(TARGET)

clean:
	rm -f $(TARGET)

